baseURL = "https://rafaam11.github.io/"
languageCode = "ko-kr"
defaultContentLanguage = "ko"
title = "rafaam11's blog"
theme = "PaperMod"
paginate = 10
enableRobotsTXT = true
buildDrafts = false
buildFuture = false

[minify]
  disableXML = true
  minifyOutput = true

[outputs]
  home = ["HTML", "RSS", "JSON"]

[taxonomies]
  category = "categories"
  tag = "tags"

[params]
  env = "production"
  author = "rafaam11"
  description = "개발과 일상을 기록합니다."

  ShowReadingTime = true
  ShowShareButtons = false
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = true
  ShowWordCount = true
  ShowRssButtonInSectionTermList = true
  UseHugoToc = true
  disableSpecial1stPost = false
  disableScrollToTop = false
  comments = true
  hidemeta = false
  hideSummary = false
  showtoc = false
  tocopen = false

  [params.profileMode]
    enabled = false

  [params.homeInfoParams]
    Title = "안녕하세요 👋"
    Content = "개발과 일상을 기록하는 블로그입니다."

  [[params.socialIcons]]
    name = "github"
    url = "https://github.com/rafaam11"

  [params.assets]
    disableHLJS = true

[menu]
  [[menu.main]]
    identifier = "posts"
    name = "Posts"
    url = "/posts/"
    weight = 1

  [[menu.main]]
    identifier = "categories"
    name = "Categories"
    url = "/categories/"
    weight = 2

  [[menu.main]]
    identifier = "tags"
    name = "Tags"
    url = "/tags/"
    weight = 3

  [[menu.main]]
    identifier = "archives"
    name = "Archive"
    url = "/archives/"
    weight = 4
